name: Latest blog post workflow
on:
  # schedule: # Run workflow automatically
  #   - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: 
permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull in substack posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://vserifoglu.substack.com/feed"
          user_agent: "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0"
          accept_header: "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/png,image/svg+xml,*/*;q=0.8"

